---
- hosts: all
  become: yes
 
  tasks:
  - name: Install Apache
    apt: 
      name: apache2
      update_cache: yes 
      state: latest 
  - name: Start Apache service
    service: 
      name: apache2 
      state: started 
      enabled: yes 
  - name: Transfer files
    copy: 
      src: ~/ansibleWP/webprofiles
      dest: /var/www/html
      owner: www-data 
      group: www-data
      mode: 0644  
  - name: Transfer html file
    copy: 
      src: ~/ansibleWP/webprofiles/index.html
      dest: /var/www/html
      owner: www-data 
      group: www-data
      mode: 0644 
      notify: restart apache
  handlers:
    - name: restart apache
      service: name=apache2 state=restarted

    
  
